import React, { useState } from 'react';
import { Megaphone, Copy, Check, ShieldAlert, Radio } from 'lucide-react';

export default function PublicAlertPanel({ alert }) {
  const [copied, setCopied] = useState(false);

  if (!alert) return null;

  const handleCopy = () => {
    const textToCopy = `${alert.title}\nTarget Zone: ${alert.target_zone}\nApproved Route: ${alert.approved_route}\n\n${alert.message}\n\n[${alert.label}]`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900/90 border border-amber-500/40 rounded-2xl p-5 shadow-2xl glass-card relative overflow-hidden">
      
      {/* Background Glow */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between mb-4 border-b border-slate-800 pb-3 relative z-10">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-amber-500/20 border border-amber-500/30 flex items-center justify-center">
            <Megaphone className="w-4 h-4 text-amber-400" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2">
              Public Emergency Alert Draft
              <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/40">
                {alert.label}
              </span>
            </h3>
            <p className="text-xs text-slate-400">Generated by Communications Agent for immediate public broadcast</p>
          </div>
        </div>

        {/* Copy Alert Button */}
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-amber-600 hover:bg-amber-500 text-white font-mono text-xs font-bold transition-all shadow-md cursor-pointer"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-white" /> : <Copy className="w-3.5 h-3.5 text-white" />}
          <span>{copied ? 'ALERT COPIED!' : '[ COPY ALERT ]'}</span>
        </button>
      </div>

      {/* Alert Body */}
      <div className="bg-slate-950/90 border border-amber-500/30 rounded-xl p-4 font-mono space-y-3 relative z-10">
        <div className="flex items-center justify-between text-amber-400 font-bold text-sm">
          <span>{alert.title}</span>
          <span className="text-[10px] text-slate-400">{alert.timestamp}</span>
        </div>

        <div className="grid grid-cols-2 gap-2 text-xs text-slate-300 bg-slate-900/80 p-2.5 rounded border border-slate-800">
          <div>
            <span className="text-slate-400 uppercase">Target Sector:</span>{' '}
            <strong className="text-white">{alert.target_zone}</strong>
          </div>
          <div>
            <span className="text-slate-400 uppercase">Approved Route:</span>{' '}
            <strong className="text-emerald-400">{alert.approved_route}</strong>
          </div>
        </div>

        <p className="text-xs text-slate-200 leading-relaxed font-sans bg-slate-900/50 p-3 rounded border border-slate-800 italic">
          "{alert.message}"
        </p>
      </div>

    </div>
  );
}
